export const GET_SUPER_ADMIN_PENDING = 'GET_SUPER_ADMIN_PENDING';
export const GET_SUPER_ADMIN_SUCCESS = 'GET_SUPER_ADMIN_SUCCESS';
export const GET_SUPER_ADMIN_ERROR = 'GET_SUPER_ADMIN_ERROR';
export const DELETE_SUPER_ADMIN_PENDING = 'DELETE_SUPER_ADMIN_PENDING;';
export const DELETE_SUPER_ADMIN_SUCCESS = 'DELETE_SUPER_ADMIN_SUCCESS';
export const DELETE_SUPER_ADMIN_ERROR = 'DELETE_SUPER_ADMIN_ERROR';
export const CLOSE_MESSAGE_MODAL = 'CLOSE_MESSAGE_MODAL';
