export const GET_SUPER_ADMINS_PENDING = 'GET_SUPER_ADMINS_PENDING';
export const GET_SUPER_ADMINS_SUCCESS = 'GET_SUPER_ADMINS_SUCCESS';
export const GET_SUPER_ADMINS_ERROR = 'GET_SUPER_ADMINS_ERROR';

export const GET_BY_ID_SUPER_ADMINS_PENDING = 'GET_BY_ID_SUPER_ADMINS_PENDING';
export const GET_BY_ID_SUPER_ADMINS_SUCCESS = 'GET_BY_ID_SUPER_ADMINS_SUCCESS';
export const GET_BY_ID_SUPER_ADMINS_ERROR = 'GET_BY_ID_SUPER_ADMINS_ERROR';

export const POST_SUPER_ADMINS_PENDING = 'POST_SUPER_ADMINS_PENDING;';
export const POST_SUPER_ADMINS_SUCCESS = 'POST_SUPER_ADMINS_SUCCESS';
export const POST_SUPER_ADMINS_ERROR = 'POST_SUPER_ADMINS_ERROR';

export const UPDATE_SUPER_ADMINS_PENDING = 'UPDATE_SUPER_ADMINS_PENDING;';
export const UPDATE_SUPER_ADMINS_SUCCESS = 'UPDATE_SUPER_ADMINS_SUCCESS';
export const UPDATE_SUPER_ADMINS_ERROR = 'UPDATE_SUPER_ADMINS_ERROR';

export const DELETE_SUPER_ADMINS_PENDING = 'DELETE_SUPER_ADMINS_PENDING;';
export const DELETE_SUPER_ADMINS_SUCCESS = 'DELETE_SUPER_ADMINS_SUCCESS';
export const DELETE_SUPER_ADMINS_ERROR = 'DELETE_SUPER_ADMINS_ERROR';

export const MESSAGE_MODAL_OPEN = 'MESSAGE_MODAL_OPEN';
export const MESSAGE_MODAL_CLOSE = 'MESSAGE_MODAL_CLOSE';
export const CONFIRM_MODAL_OPEN = 'CONFIRM_MODAL_OPEN';
export const CONFIRM_MODAL_CLOSE = 'CONFIRM_MODAL_CLOSE';
export const PASSWORD_MODAL_OPEN = 'PASSWORD_MODAL_OPEN';
export const PASSWORD_MODAL_CLOSE = 'PASSWORD_MODAL_CLOSE';
