export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING;';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const DELETE_EMPLOYEES_PENDING = 'DELETE_EMPLOYEES_PENDING;';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_ERROR = 'DELETE_EMPLOYEES_ERROR';

export const CLOSE_MESSAGE_MODAL = 'CLOSE_MESSAGE_MODAL';
export const CONFIRM_MODAL_OPEN = 'CONFIRM_MODAL_OPEN';
export const CONFIRM_MODAL_CLOSE = 'CONFIRM_MODAL_CLOSE';
