export const GET_EMPLOYEES_LOADING = 'GET_EMPLOYEES_LOADING;';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const CLOSE_MESSAGE_MODAL = 'CLOSE_MESSAGE_MODAL';
