export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const GETBYID_TASK_PENDING = 'GETBYID_TASK_PENDING;';
export const GETBYID_TASK_SUCCESS = 'GETBYID_TASK_SUCCESS';
export const GETBYID_TASK_ERROR = 'GETBYID_TASK_ERROR';

export const CREATE_TASKS_PENDING = 'CREATE_TASKS_PENDING';
export const CREATE_TASKS_SUCCESS = 'CREATE_TASKS_SUCCESS';
export const CREATE_TASKS_ERROR = 'CREATE_TASKS_ERROR';

export const UPDATE_TASKS_PENDING = 'UPDATE_TASKS_PENDING';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';
export const UPDATE_TASKS_ERROR = 'UPDATE_TASKS_ERROR';

export const DELETE_TASKS_PENDING = 'DELETE_TASKS_PENDING';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_ERROR = 'DELETE_TASKS_ERROR';

export const MESSAGE_MODAL_OPEN = 'MESSAGE_MODAL_OPEN';
export const MESSAGE_MODAL_CLOSE = 'MESSAGE_MODAL_CLOSE';
export const CONFIRM_MODAL_OPEN = 'CONFIRM_MODAL_OPEN';
export const CONFIRM_MODAL_CLOSE = 'CONFIRM_MODAL_CLOSE';
