export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const POST_TIMESHEETS_PENDING = 'POST_TIMESHEETS_PENDING';
export const POST_TIMESHEETS_SUCCES = 'POST_TIMESHEETS_SUCCES';
export const POST_TIMESHEETS_ERROR = 'POST_TIMESHEETS_ERROR';

export const CLOSE_MESSAGE_MODAL = 'CLOSE_MESSAGE_MODAL';
export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
