export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';
export const TOGGLE_MESSAGE_MODAL = 'TOGGLE_MESSAGE_MODAL';
